// SPDX-License-Identifier: MIT
// rdna3_perf_envelope.h — GENERATED constants from measured latency envelope.
//
// This file should be REGENERATED by running the udi microbench suite and
// emitting fresh constants. Do not hand-edit. Hand-edits are stale by definition.
//
// Generation source: exterior_algebra/results/{launch_overhead,signal_latency_floor,
// dual_megakernel,megakernel_skeleton,megakernel_fanout,megakernel_under_load_rt,
// sdma_latency_curve,cross_gpu_write_latency,wedge_repro_matrix}.json.
//
// The constants below are MEDIAN values under proper CPU isolation (CPU 55
// SCHED_FIFO). p99 and worst-case are also exposed. Values below are appropriate
// for budgeting decisions, NOT for tight hot-path scheduling — measure your own
// workload if scheduling depends on these.

#pragma once

// Generation provenance — visible to anyone reading the header.
#define RDNA3_PERF_GENERATED_HW         "gfx1100"
#define RDNA3_PERF_GENERATED_ROCM       "7.2.3"
#define RDNA3_PERF_GENERATED_DATE       "2026-05-13"
#define RDNA3_PERF_GENERATED_HOST       "8x RX 7900 XTX, EPYC 7532"
#define RDNA3_PERF_GENERATED_CPU_ISO    "isolcpus=55-63 nohz_full=55-63 rcu_nocbs=55-63"

// CPU↔GPU primitives (single-GPU, CPU 55 SCHED_FIFO)
#define RDNA3_PERF_HIPLAUNCH_API_RETURN_US      1.65    // empty kernel, no args
#define RDNA3_PERF_HIPLAUNCH_PER_ARG_OVERHEAD_NS  60    // ~60ns per pointer arg
#define RDNA3_PERF_HIPLAUNCH_WARM_SYNC_US         26    // launch + hipDeviceSynchronize
#define RDNA3_PERF_HIPLAUNCH_COLD_SYNC_US        142    // first launch in a new stream
#define RDNA3_PERF_HIPGRAPH_LAUNCH_US             10    // single-node graph (slower!)

// GPU→pinned-host signal latency floor (single-GPU)
#define RDNA3_PERF_GPU_TO_CPU_SIGNAL_MEDIAN_NS   310    // hipHostMallocMapped
#define RDNA3_PERF_GPU_TO_CPU_SIGNAL_P99_NS      670

// Cross-GPU primitives (two persistent megakernels, peer-VRAM, no CPU in loop)
#define RDNA3_PERF_CROSS_GPU_PEER_WRITE_HW_FLOOR_US   1.2   // hardware physics floor
#define RDNA3_PERF_DUAL_MEGAKERNEL_RTT_MIN_US         2.58
#define RDNA3_PERF_DUAL_MEGAKERNEL_RTT_MEDIAN_US      3.73
#define RDNA3_PERF_DUAL_MEGAKERNEL_RTT_P99_US         3.92

// Persistent megakernel CPU↔GPU dispatch (one persistent kernel, CPU triggers via doorbell)
#define RDNA3_PERF_MEGAKERNEL_DISPATCH_MEDIAN_US  2.79
#define RDNA3_PERF_MEGAKERNEL_DISPATCH_MIN_US     2.58
#define RDNA3_PERF_MEGAKERNEL_DISPATCH_P99_US     2.88

// 1→N GPU fan-out (1 CPU dispatch, N persistent kernels ack)
#define RDNA3_PERF_FANOUT_1GPU_MEDIAN_US   1.62
#define RDNA3_PERF_FANOUT_2GPU_MEDIAN_US   2.16
#define RDNA3_PERF_FANOUT_4GPU_MEDIAN_US   2.53
#define RDNA3_PERF_FANOUT_8GPU_MEDIAN_US   2.87

// SDMA / blit-kernel transfer envelope (see rdna3_sdma.h for full curve)
#define RDNA3_PERF_BLIT_KERNEL_FLOOR_US      15
#define RDNA3_PERF_SDMA_THRESHOLD_BYTES      1048576
#define RDNA3_PERF_SDMA_PEAK_THROUGHPUT_GBS  6.313

// Under-load degradation (CPU 55 SCHED_FIFO, vs idle baseline)
// Tested under: same-GPU SGEMM, peer-GPU SGEMM, peer-PCIe-heavy, CPU stress.
// All scenarios ≤1.01x p50 degradation, ≤1.00x p99 degradation.
#define RDNA3_PERF_UNDER_LOAD_P50_DEGRADATION  1.01
#define RDNA3_PERF_UNDER_LOAD_P99_DEGRADATION  1.00

// Multi-GPU wedge envelope (V7 minimal repro, see results/wedge_repro_matrix.json)
// Cross-GPU peer-UC store + persistent + post-poll atomic_block_barrier wedges
// at ~30% rate under 4-GPU envelope. NEVER write this pattern outside the
// rdna3_peer_write_deferred primitive — see rdna3_peer.h §11.4 hazard.
#define RDNA3_PERF_WEDGE_V7_RATE  0.30
