use braidinfer_core::types::DeviceId;
use braidinfer_hip::HipResult;
use braidinfer_hip::memory::{DeviceBuffer, MappedHostBuffer};
use braidinfer_hip::module::Module;
use braidinfer_hip::stream::Stream;
use std::ffi::c_void;
use std::sync::Arc;

use crate::config::ModelConfig;
use crate::tracer::TraceSink;
use crate::watchdog::WatchdogThread;

/// Tokens per paged KV chunk — must match compile_attention_layer_paged.
pub const CHUNK_TOKENS: usize = 64;

// Opcode constants — auto-generated from kernels/opcodes.h (single source of truth)
include!(concat!(env!("BRAIDINFER_KERNEL_DIR"), "/opcodes.rs"));

// Canonical instruction-ABI constants — auto-generated by braidinfer-hip's build.rs
// from kernels/megakernel_common.h (INST_SIZE_WORDS) + worker_queue.h
// (MAX_BATCH_INSTRUCTIONS). Exposes KERNEL_INST_SIZE_WORDS + KERNEL_MAX_BATCH_INSTRUCTIONS.
// The compile-time asserts on INST_SIZE (below) and MAX_BATCH_INSTRUCTIONS
// (persistent_dispatch.rs) guarantee the Rust and C definitions never drift — a drift
// is a COMPILE error, not a silent runtime ABI mismatch (cf. the stale prod_kernel_test
// INST_SIZE_WORDS 18-vs-19 false-wedge).
include!(concat!(env!("BRAIDINFER_KERNEL_DIR"), "/kernel_abi.rs"));

/// Shared memory bytes per block for tiled-LDS linear_proj ops: (8 + 7680 + 256) * 4.
/// Must match SHARED_LPROJ_TOTAL in kernels/megakernel_ops.hip.
pub const SHARED_LPROJ_TOTAL: u32 = 31776;

pub const INST_SIZE: usize = 19; // 19 u64s per instruction = 152 bytes (bd srg6.2)
// Cross-language ABI guard: the Rust INST_SIZE MUST equal the C kernel's
// INST_SIZE_WORDS (kernels/megakernel_common.h), parsed by build.rs. Drift =>
// compile error here, instead of a silent wrong-stride / wrong-offset ABI bug.
const _: () = assert!(
    INST_SIZE == KERNEL_INST_SIZE_WORDS,
    "ABI drift: Rust INST_SIZE != C INST_SIZE_WORDS (kernels/megakernel_common.h)"
);
// RDNA3 7900XTX: 96 CUs grouped into 48 WGPs. hipDeviceAttributeMultiprocessorCount=48 (WGPs).
// Cooperative kernel max blocks = blocks_per_sm * WGPs = blocks_per_sm * 48.
pub(crate) const NUM_CUS: u32 = 48;

/// A single instruction for the megakernel program.
#[derive(Clone)]
pub struct Instruction {
    pub(crate) words: [u64; INST_SIZE],
}

impl Instruction {
    pub(crate) fn new(opcode: u32, grid_x: u32) -> Self {
        let mut words = [0u64; INST_SIZE];
        words[0] = (opcode as u64) | ((grid_x as u64) << 32);
        Instruction { words }
    }

}

/// KV cache configuration used on ALL programs (paged and non-paged, decode and prefill).
pub(crate) struct KvConfig {
    pub max_seq_len: u32,
    pub num_kv_heads: usize,
    pub head_dim: usize,
    pub kv_write_indices: Vec<Vec<(usize, usize)>>, // per attn layer, per kv_head: (k_copy_idx, v_copy_idx)
    pub kv_base_ptrs: Vec<(u64, u64)>,              // (k_base, v_base) per attention layer
}

/// Paged KV cache state — only populated when `paged=true`.
/// `attn_quant_inst_indices` lives here (not in QuantizedKvState) because
/// `update_step_paged` iterates it unconditionally on all paged programs
/// (to disable OP_ATTN_PAGED_Q when quantized_kv=false).
pub(crate) struct PagedKvState {
    /// page_table is host-mapped so updates from CPU are immediately visible to the
    /// persistent cooperative kernel without hipMemcpyAsync (which would deadlock
    /// per the HIP API prohibition documented in persistent_dispatch.rs).
    pub page_table: Option<MappedHostBuffer<u64>>,
    pub position_table: Option<MappedHostBuffer<i32>>,
    pub attn_paged_inst_indices: Vec<usize>,
    pub attn_quant_inst_indices: Vec<usize>,
    pub last_page_table_len: usize,
    /// Set to `true` by the prefetch pass (Phase D) whenever a tier transition
    /// (promote or evict) changes a chunk's VRAM slot_ptr without changing
    /// `seq.chunks.len()`.  Cleared to `false` by `update_step_paged_no_upload`
    /// after the write_volatile loop executes.  Prevents the count-guard from
    /// skipping a necessary page_table rewrite on tier transitions (B1 fix).
    pub page_table_dirty: bool,
    pub kv_stride_paged: usize,
}

/// Quantized KV state — only populated when `quantized_kv=true`.
pub(crate) struct QuantizedKvState {
    /// VRAM scratch region (nqh × (2 + hd) f32s per attention layer) for
    /// OP_ATTN_PAGED_Q's partial_state accumulators. The DeviceBuffer is
    /// never read by Rust after enable_quantized_kv() patches its `as_ptr()`
    /// into the OP_ATTN_PAGED_Q + OP_ATTN_PAGED instruction `scratch` /
    /// `partial_state` fields (megakernel_run.rs:626-645). This Option keeps
    /// the underlying allocation alive for the program's lifetime — the GPU
    /// kernel reads/writes via the baked-in raw pointer.
    /// bd loyy 2026-05-21: was #[allow(dead_code)]; replaced with doc comment.
    /// Field MUST remain even though dead_code lint would flag — dropping it
    /// would free VRAM the kernel still has pointers into.
    #[allow(dead_code)]  // RAII anchor, see doc above
    pub quant_scratch: Option<DeviceBuffer<f32>>,
    /// Host-mapped (MappedHostBuffer) to avoid hipMemcpy under the persistent
    /// cooperative kernel. Same pattern as page_table. Written from CPU via
    /// host_ptr().write_volatile when a chunk seals (~once per 64 tokens);
    /// read from GPU via device_ptr() patched into OP_ATTN_PAGED_Q instructions.
    pub quant_page_table: Option<MappedHostBuffer<u64>>,
    pub last_quant_page_table_len: usize,
}

/// Set opcode + weight pointer for a linear projection instruction.
/// For bf16: keeps OP_LINEAR_PROJ, sets bf16 pointer.
/// For packed: switches opcode to OP_LINEAR_PROJ_RNF4/PCG32, sets u8 pointer.
pub struct MegakernelProgram {
    pub(crate) instructions: Vec<Instruction>,
    pub(crate) num_blocks: u32,
    pub(crate) device: DeviceId,
    // Indices of instructions that need per-step updates
    pub(crate) embedding_inst_idx: usize,
    pub(crate) gqa_attn_inst_indices: Vec<usize>, // seq_len changes each step
    // KV cache config (mandatory — present on all programs)
    pub(crate) kv: KvConfig,
    // Paged KV cache support (Some only when paged=true)
    pub(crate) paged: bool,
    pub(crate) paged_kv: Option<PagedKvState>,
    // Quantized KV support (Some only when quantized_kv=true)
    pub quantized_kv: bool,
    pub(crate) quant_kv: Option<QuantizedKvState>,
    // Dump mode: per-instruction activation capture.
    // dump_counter is host-mapped (MappedHostBuffer) so we can initialize it
    // and read/reset it from the CPU without a hipMemcpy — the persistent
    // cooperative kernel holds CUs and would deadlock on copy_from_host.
    // GPU side does atomicAdd on host-mapped UC memory (validated wt1 pattern).
    pub(crate) dump_buffer: Option<DeviceBuffer<u8>>, // slot data
    pub(crate) dump_counter: Option<MappedHostBuffer<i32>>, // atomic slot counter (host-mapped)
    pub(crate) dump_capacity: i32,
    /// (instruction_idx, layer_idx) for each OP_BARRIER in the program.
    /// CPU dispatch loop uses layer_idx to look up DistributedMoeWeights.
    pub(crate) barrier_layer_map: Vec<(usize, usize)>,
    pub(crate) _mrope_inst_indices: Vec<usize>,
    // Multi-GPU distributed QKV projection boundaries (only used when multi_gpu=true).
    // For each attention layer: (rmsnorm_idx, output_gate_idx) where:
    //   rmsnorm_idx  = index of the RMSNorm instruction (flush + dispatch QKV/GQA after this)
    //   output_gate_idx = index of OP_OUTPUT_GATE or O-proj (resume megakernel here after dispatch)
    pub(crate) multi_gpu_attn_boundaries: Vec<(usize, usize)>,
    // Prevent Send — contains raw GPU device pointers as u64
    pub(crate) _not_send: std::marker::PhantomData<*mut ()>,
    /// Map from instruction index → Probe emitted at that instruction (when
    /// dump_buffer is enabled). Populated at compile time by emit_attention_layer
    /// / compile_gdn_layer / compile_ffn / compile_embedding sites. Drained by
    /// PersistentDispatch::drain_trace_dump.
    pub(crate) trace_probe_map: Vec<(usize, crate::tracer::Probe)>,
    /// Shared watchdog (Arc from Model). Kept alive here so the thread is not
    /// stopped while this program is in use.
    pub(crate) _watchdog: std::sync::Arc<WatchdogThread>,
}

/// Activation buffers sized for N-token prefill chunks.
/// All buffers are [batch × dim] where batch = chunk_tokens.
pub struct PrefillBuffers {
    pub hidden: DeviceBuffer<f32>,  // [N × hidden_size] — main hidden state
    pub normed: DeviceBuffer<f32>,  // [N × hidden_size]
    pub qkv: DeviceBuffer<f32>,     // [N × conv_dim] (6144 for Qwen3.5)
    pub a_proj: DeviceBuffer<f32>,  // [N × num_heads]
    pub b_proj: DeviceBuffer<f32>,  // [N × num_heads]
    pub z_proj: DeviceBuffer<f32>,  // [N × num_heads * value_dim]
    pub ffn_act: DeviceBuffer<f32>, // [N × intermediate_size]
    pub residual: DeviceBuffer<f32>, // [N × hidden_size]
    // bd pywl: host-mapped so write_positions writes via CPU MMIO instead of
    // hipMemcpy. PrefillBuffers's write_positions runs from Model::prefill,
    // which (under always-persistent, post bd 9gmh Phase 2) happens AFTER the
    // worker spawn — synchronous hipMemcpy on GPU 0 deadlocks against the
    // cooperative kernel holding all CUs.
    pub position_ids: MappedHostBuffer<i32>, // [N × 3] — mRoPE positions per token
    // Attention layer intermediates
    pub q_gate_attn: DeviceBuffer<f32>, // [N × nqh × hd × 2]
    pub q_attn: DeviceBuffer<f32>,      // [N × nqh × hd]
    pub k_attn: DeviceBuffer<f32>,      // [N × nkh × hd]
    pub v_attn: DeviceBuffer<f32>,      // [N × nkh × hd]
    pub gate_attn: DeviceBuffer<f32>,   // [N × nqh × hd]
    pub attn_out: DeviceBuffer<f32>,    // [N × nqh × hd]
    pub gated_out: DeviceBuffer<f32>,   // [N × nqh × hd]
    pub out_proj: DeviceBuffer<f32>,    // [N × hidden_size]
    // Single-token scratch for quantized FFN unfused path (Q4 prefill)
    pub ffn_gate_scratch: DeviceBuffer<f32>, // [intermediate_size]
    pub ffn_up_scratch: DeviceBuffer<f32>,   // [intermediate_size]
    pub ffn_down_scratch: DeviceBuffer<f32>, // [hidden_size]
}

impl PrefillBuffers {
    /// Refresh `position_ids` for an N-token chunk starting at `start_pos`.
    /// MUST be called before every execute() of a prefill_segment program — the
    /// program is keyed by start_pos but position_ids is a SHARED buffer that
    /// other cached programs may have overwritten since the last execute.
    /// Without this refresh, the second run of bench_coherence reads stale
    /// positions from the previous run's last prefill (5ax root cause).
    pub fn write_positions(&mut self, start_pos: u32, n: usize) -> HipResult<()> {
        // bd pywl: host-mapped UC write — GPU reads through device_ptr without
        // hipMemcpy. Safe under the running persistent worker.
        let host_ptr = self.position_ids.host_ptr();
        for t in 0..n {
            let pos = (start_pos + t as u32) as i32;
            unsafe {
                host_ptr.add(t * 3).write_volatile(pos);
                host_ptr.add(t * 3 + 1).write_volatile(pos);
                host_ptr.add(t * 3 + 2).write_volatile(pos);
            }
        }
        Ok(())
    }
}

impl PrefillBuffers {
    pub fn alloc(device: DeviceId, cfg: &ModelConfig, chunk_tokens: usize) -> HipResult<Self> {
        let n = chunk_tokens;
        let hs = cfg.hidden_size;
        let nh = cfg.linear_num_heads;
        let nvh = cfg.linear_num_value_heads;
        let kd = cfg.linear_key_head_dim;
        let vd = cfg.linear_value_head_dim;
        let conv_dim = nh * kd * 2 + nvh * vd;
        let is = cfg.intermediate_size;
        let nqh = cfg.num_q_heads;
        let nkh = cfg.num_kv_heads;
        let hd = cfg.head_dim;
        Ok(PrefillBuffers {
            hidden: DeviceBuffer::alloc(device, n * hs)?,
            normed: DeviceBuffer::alloc(device, n * hs)?,
            qkv: DeviceBuffer::alloc(device, n * conv_dim)?,
            // a_proj/b_proj are written by w_a/w_b linear projections in compile_prefill
            // with output_dim = nvh (one log-decay per value head, then GQA-expanded).
            // Allocating n*nh here was a latent OOB whenever nvh > nh (e.g. Qwen3.5-A3B,
            // 4B: nvh=32 vs nh=16). The batched linear_proj wrote n*(nvh-nh) floats past
            // the end of the buffer, faulting at the first unmapped page.
            a_proj: DeviceBuffer::alloc(device, n * nvh)?,
            b_proj: DeviceBuffer::alloc(device, n * nvh)?,
            z_proj: DeviceBuffer::alloc(device, n * nvh * vd)?,
            ffn_act: DeviceBuffer::alloc(device, n * is)?,
            residual: DeviceBuffer::alloc(device, n * hs)?,
            position_ids: MappedHostBuffer::<i32>::alloc(n * 3)?,
            q_gate_attn: DeviceBuffer::alloc(
                device,
                n * nqh * hd * if cfg.has_output_gate { 2 } else { 1 },
            )?,
            q_attn: DeviceBuffer::alloc(device, n * nqh * hd)?,
            k_attn: DeviceBuffer::alloc(device, n * nkh * hd)?,
            v_attn: DeviceBuffer::alloc(device, n * nkh * hd)?,
            gate_attn: DeviceBuffer::alloc(device, n * nqh * hd)?,
            attn_out: DeviceBuffer::alloc(device, n * nqh * hd)?,
            gated_out: DeviceBuffer::alloc(device, n * nqh * hd)?,
            out_proj: DeviceBuffer::alloc(device, n * hs)?,
            ffn_gate_scratch: DeviceBuffer::alloc(device, is)?,
            ffn_up_scratch: DeviceBuffer::alloc(device, is)?,
            ffn_down_scratch: DeviceBuffer::alloc(device, hs)?,
        })
    }
}

pub(crate) mod instructions;
pub(crate) use instructions::*;

/// bd srg6.4 Phase 3b: thin public facade for the OP_KV_WRITE_PAGED_BATCH
/// integration test. Exposes only the items the test needs to construct
/// raw Instructions and dispatch them via PersistentDispatch.
/// Not intended for production use.
#[doc(hidden)]
pub mod srg6_4_test_api {
    pub use super::INST_SIZE;
    pub use super::Instruction;
    pub use super::SHARED_LPROJ_TOTAL;
    pub use super::instructions::{D2dCopyInst, KvWritePagedBatchInst};
    pub use super::OP_HALT;

    impl Instruction {
        #[doc(hidden)]
        pub fn test_new(opcode: u32, grid_x: u32) -> Self {
            Self::new(opcode, grid_x)
        }
    }

    impl D2dCopyInst {
        #[doc(hidden)]
        #[allow(clippy::new_ret_no_self)]
        pub fn test_new(grid_x: u32, dst: *mut f32, src: *const f32, n_elems: i32) -> Self {
            Self::new(grid_x, dst, src, n_elems)
        }
    }

    impl KvWritePagedBatchInst {
        #[doc(hidden)]
        #[allow(clippy::too_many_arguments)]
        pub fn test_new(
            src: *const f32,
            page_table: *const u64,
            layer_kv_offset: u64,
            start_pos: u32,
            n_tokens: u32,
            local_kv_head_start: u16,
            local_nkh: u16,
            head_dim: u16,
            chunk_tokens: u16,
        ) -> Self {
            Self::new(
                src,
                page_table,
                layer_kv_offset,
                start_pos,
                n_tokens,
                local_kv_head_start,
                local_nkh,
                head_dim,
                chunk_tokens,
            )
        }
    }
}

pub(crate) mod compile_common;
mod compile_attention;
mod compile_layers;
mod compile_moe;
mod megakernel_compile;
mod megakernel_run;

impl MegakernelProgram {
    pub fn instruction_count(&self) -> usize {
        self.instructions.len()
    }
    pub fn block_count(&self) -> u32 {
        self.num_blocks
    }

    /// Read dump results after execute. Returns Vec of (opcode, inst_idx, data).
    pub fn read_dump(&self, stream: &Stream) -> HipResult<Vec<(u32, u32, Vec<f32>)>> {
        const DUMP_SLOT_BYTES: usize = 16 + 8192 * 4;
        let counter = self.dump_counter.as_ref().unwrap();
        stream.synchronize()?;
        let count_val = unsafe { *counter.host_ptr() };
        let num_slots = count_val.min(self.dump_capacity) as usize;

        let buf = self.dump_buffer.as_ref().unwrap();
        let total_bytes = num_slots * DUMP_SLOT_BYTES;
        let mut host = vec![0u8; total_bytes];
        if num_slots > 0 {
            braidinfer_hip::error::check(unsafe {
                braidinfer_hip::ffi::hipMemcpyAsync(
                    host.as_mut_ptr() as *mut std::ffi::c_void,
                    buf.as_ptr() as *const std::ffi::c_void,
                    total_bytes,
                    braidinfer_hip::ffi::hipMemcpyDeviceToHost,
                    stream.raw(),
                )
            })?;
            stream.synchronize()?;
        }

        let mut results = Vec::with_capacity(num_slots);
        for i in 0..num_slots {
            let slot = &host[i * DUMP_SLOT_BYTES..];
            let opcode = u32::from_le_bytes(slot[0..4].try_into().unwrap());
            let inst_idx = u32::from_le_bytes(slot[4..8].try_into().unwrap());
            let size = u32::from_le_bytes(slot[8..12].try_into().unwrap()) as usize;
            let data: Vec<f32> = (0..size)
                .map(|j| {
                    let off = 16 + j * 4;
                    f32::from_le_bytes(slot[off..off + 4].try_into().unwrap())
                })
                .collect();
            results.push((opcode, inst_idx, data));
        }
        Ok(results)
    }

    /// Enable per-instruction dump mode for the persistent worker path.
    /// Allocates the VRAM dump buffer + host-mapped counter. The persistent_worker
    /// reads dump pointers from `WorkerQueue.dump_base/count/capacity` (written by
    /// `PersistentDispatch::set_trace_dump_ptrs`), not from a NOP header.
    ///
    /// Safe to call while the persistent worker is running because it does not
    /// issue any HIP API that requires free CUs.
    pub fn enable_dump_persistent(&mut self, max_slots: i32) -> HipResult<()> {
        const DUMP_SLOT_BYTES: usize = 16 + 8192 * 4;
        let buf_size = max_slots as usize * DUMP_SLOT_BYTES;
        self.dump_buffer = Some(DeviceBuffer::<u8>::alloc(self.device, buf_size)?);
        let counter = MappedHostBuffer::<i32>::alloc(1)?;
        unsafe { *counter.host_ptr() = 0i32; }
        self.dump_counter = Some(counter);
        self.dump_capacity = max_slots;
        Ok(())
    }

    pub fn dump_active(&self) -> bool {
        self.dump_buffer.is_some()
    }

    /// Write dump results to a BTRC trace file compatible with compare_traces.py.
    /// Names are derived from opcode + sequential index (e.g., "inst003_LINEAR_PROJ").
    pub fn write_dump_btrc(&self, stream: &Stream, path: &str) -> HipResult<()> {
        let slots = self.read_dump(stream)?;
        let mut tw = TraceSink::open(path).expect("failed to open dump trace file");
        for (opcode, inst_idx, data) in &slots {
            let name = format!("inst{:03}_{}", inst_idx, opcode_name(*opcode));
            tw.write_checkpoint(&name, data).expect("failed to write checkpoint");
        }
        tw.close().expect("failed to close dump trace file");
        eprintln!(
            "Megakernel dump: {} instructions written to {}",
            slots.len(),
            path
        );
        Ok(())
    }

    /// Route this program's instruction stream through the persistent worker
    /// mailbox.
    ///
    /// Worker must already be spawned on this program's device — caller
    /// (Model::prefill / decode_step_persistent) handles spawn ordering.
    /// dispatch_batch_slice chunks into MAX_BATCH_INSTRUCTIONS=256 slices
    /// and wait_acks each slice synchronously (no separate stream sync needed).
    ///
    /// Dump-buffer note: worker reads dump_base / dump_count from
    /// WorkerQueueLayout (populated by PersistentDispatch::set_trace_dump_ptrs).
    pub fn dispatch_via_worker(
        &mut self,
        dispatch: &mut crate::persistent_dispatch::PersistentDispatch,
        gpu_idx: usize,
    ) -> HipResult<()> {
        // persistent_worker exits on OP_HALT (kernels/megakernel.hip:231-237).
        // Compiled prefill programs append OP_HALT historically; strip it so
        // the worker stays alive for subsequent batches.
        let halt_idx = self.instructions.iter()
            .position(|inst| (inst.words[0] as u32) == OP_HALT)
            .unwrap_or(self.instructions.len());
        dispatch.dispatch_batch_slice(gpu_idx, &self.instructions[..halt_idx]);
        Ok(())
    }
}

pub fn opcode_name_str(op: u32) -> String {
    opcode_name(op).to_string()
}

fn opcode_name(op: u32) -> &'static str {
    match op {
        OP_NOP => "NOP",
        OP_RMSNORM => "RMSNORM",
        OP_LINEAR_PROJ => "LINEAR_PROJ",
        OP_CONV1D => "CONV1D",
        OP_GDN_GATE => "GDN_GATE",
        OP_GDN_RECUR => "GDN_RECUR",
        OP_RMSNORM_GATE => "RMSNORM_GATE",
        OP_RESIDUAL_ADD => "RESIDUAL_ADD",
        OP_QK_NORM => "QK_NORM",
        OP_MROPE => "MROPE",
        OP_GQA_ATTN => "GQA_ATTN",
        OP_OUTPUT_GATE => "OUTPUT_GATE",
        OP_FFN_GATE_UP => "FFN_GATE_UP",
        OP_FFN_DOWN_RES => "FFN_DOWN_RES",
        OP_EMBEDDING => "EMBEDDING",
        OP_LM_HEAD => "LM_HEAD",
        OP_HALT => "HALT",
        OP_D2D_COPY => "D2D_COPY",
        OP_ATTN_PAGED => "ATTN_PAGED",
        OP_ATTN_PREFILL => "ATTN_PREFILL",
        OP_DEINTERLEAVE => "DEINTERLEAVE",
        OP_KV_QUANTIZE => "KV_QUANTIZE",
        OP_ATTN_PAGED_Q => "ATTN_PAGED_Q",
        OP_MOE_GATE => "MOE_GATE",
        OP_MOE_FFN => "MOE_FFN",
        OP_LINEAR_PROJ_RNF4 => "LINEAR_PROJ_RNF4",
        OP_LINEAR_PROJ_PCG32 => "LINEAR_PROJ_PCG32",
        OP_RMSNORM_WX => "RMSNORM_WX",
        OP_SILU_MUL => "SILU_MUL",
        OP_SSM_UPDATE => "SSM_UPDATE",
        OP_FFN_GATE_UP_RNF4 => "FFN_GATE_UP_RNF4",
        OP_FFN_DOWN_RES_RNF4 => "FFN_DOWN_RES_RNF4",
        OP_SIGMOID_WEIGHTED_ADD => "SIGMOID_WEIGHTED_ADD",
        OP_CONV1D_3X => "CONV1D_3X",
        OP_FFN_GATE_UP_WX => "FFN_GATE_UP_WX",
        OP_FFN_GATE_UP_RNF4_WX => "FFN_GATE_UP_RNF4_WX",
        OP_LINEAR_PROJ_2X => "LINEAR_PROJ_2X",
        OP_MOE_DISPATCH => "MOE_DISPATCH",
        OP_MOE_DISPATCH_POST => "MOE_DISPATCH_POST",
        OP_MOE_FFN_REMOTE => "MOE_FFN_REMOTE",
        OP_KV_WRITE_PAGED_BATCH => "KV_WRITE_PAGED_BATCH",
        _ => "UNKNOWN",
    }
}
