[package]
name = "braidinfer-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
braidinfer-core = { workspace = true }
braidinfer-hip = { workspace = true }
tokenizers = { version = "0.21", default-features = false, features = ["fancy-regex"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
minijinja = { version = "2", features = ["builtins"] }
minijinja-contrib = { version = "2", features = ["pycompat"] }
rand = "0.8"
safetensors = "0.7.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-util", "io-std", "time", "sync"] }
rayon = "1"
dirs = "6"
memmap2 = "0.9"
